# Execute API tests in tests/ with deployed API

name: V2 API Tests

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 */8 * * *"

jobs:
  main:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [15.x]
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            cd tests
            npm i 
            sudo npm i -g mocha 
            sudo npm i -g ts-node
            sudo npm i typescript
      - name: Execute tests
        run: |
            cd tests
            mocha test/v2.ts -r ts-node/register
