# Execute API tests in tests/ with deployed server

name: API Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd tests
          npm i
      - name: Execute tests
        run: |
          cd tests
          npx mocha
