# Execute API tests in tests/ with server.py running locally

name: Local API Tests

on:
  push:
    paths:
      - server.py
      - requirements.txt
      - db/**/*
      - src/*
      - tests/**/*
      - setup.sh
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
      - name: Install app requirements
        run: pip install -r requirements.txt
      - name: Start API server
        run: sh deploy.sh ${{ secrets.RS2_TOKEN }} &
      - name: Install test dependencies
        run: |
          cd tests
          npm i
      - name: Execute tests
        run: |
          cd tests
          env URL="http://127.0.0.1:8000" npx mocha